sudo: required

language: bash
services: docker

env:
  matrix:
  - RUNTIME=python2.7 VARIANT=build
  - RUNTIME=python2.7 VARIANT=run
  global:
  - REPO=tanhe123
  - secure: "E3goJHNuomqOk0LqLLTvXG7scl4OXG0tFP1phTsHTv5AXOg5ye36sD7OJTkOvC6HD2c6C0W4zkcPIFyq01aPuzTrgicxP8f+m5JV8ZknlkZ6xYMEYFy7LWtruSLIFoyZY08MmUKMih9vAOEn0HIpbyIIvMGVYvmix+QmOgYoQ/COhw8lX6JrTP67HJa7O2pIE7uVCRv40Np8iQ0pAyVI2fNfOnDoYvW+YyfsECCvPN1u5EzfRikNDIGLSsk1qXM1GN2K8PpmESXBirYckZvf3r8kwX9rpxnKW1UEc3rAsvArRqAtmGq22bH6fFoofqB9TdnCWUbq5YL0t2o8MC71W4JlPpF0f4bX3f00XqR8zdzf9AmpxcVT9G1PszyHHAays8xjK8137PKU7JMJvn2LmcCfx29iHwnlSMCZUXN/oYL4UAXonzujGAZ0kqKAl/QS4S6gKti/r/6Zj1P+vXy0YMIZbh1vpZxW97m2t6rr0Rqf8mTQ/JYQo/oZ06Gbw7KK2pcmzvKghrS8ZHD+wXTSrmcxQ0LgqFtRnXVOex+ZXEsv+qA7fZF4tqdfA3+2KJPw0JNskltnmi8etpW1Q3M5O88sHYphBA2ED1hsr3/ExMX0aASLzwqwMoDmc971ftNqoA9LJvDVBfZh+qWXlaTdm0OZSZX7rnF6D7v/qcEBUgo="
  - secure: "R/jEDhEdaAPYgY1+/5Si0xGA/NZq/2Mdb+xssXjHyQ9O1gRx6ylPY4vbbL59PfY/92zorRg3P8RXySrNwmxxx6qPKALUmGg9BBfCg86+Finqdo0UDxFw+YCEL1e3k2qg2cbedtYW55IUTc9g6exa9JYvH64EyxlQRW6d531OOu4pCO7bVTnCOYZcDXdnZXDXeCQPbd5RBIQMjVLF91hGU3M5hh9T7sigB/79midVSOjdKCsWGtZYIh201DQgYGsH2mFkp93eVQgBc+eVKbP5nNXDQTUVFiSgyEFl6Ci5qdDHZbCMOly4WsNLDyc+L+/zhuB/eRfOh1aX8+75MIknEU331RDPs8EuFEsVq5WXSJjkVdJBYgHtT+g05Htpn9N5O3toBlkCVTz4Szw83WuUgVBVi1NZl2sw/ICzYKOSLezsN3c9Y5povYeyzIiCssNRUmc6yE1BUBIvv9iO78gcYLHfRwC3tS65XWkwJDDeG0O7ekmePcHdZPV79Vuj/ehITj3xciuB12CTADw6qclggT4X2/o8EFUwIIYBMkFzbWN8dcpFSg2DHnddzgiiDE/bz2U4uVxjyU57n5UTpuSSYAQZAtB70u4M96/P1pFF/ASWAAIh3dHpchj5mOzp09q44/RF2k3Q4WL0niVXMbmyRJnGLkZcPtRHaZQuX3TOq18="


  # - RUNTIME=python3.6 VARIANT=build
  # - RUNTIME=nodejs4.4 VARIANT=build
  # - RUNTIME=nodejs6.10.3 VARIANT=build
  # - RUNTIME=nodejs8 VARIANT=build
  # - RUNTIME=java8 VARIANT=build

before_script:
  - env | sort
  - if [ "run" != "$VARIANT" ]; then IMAGE_TAG="$VARIANT" && echo "$IMAGE_TAG"; fi # build or empty
  - WITH_VERSION=${TRAVIS_TAG:+$IMAGE_TAG-$TRAVIS_TAG} && echo "WITH_VERSION=$WITH_VERSION" # build or empty or build-version or -version
  - IMAGE_TAG=${WITH_VERSION:-$IMAGE_TAG} && echo "IMAGE_TAG=$IMAGE_TAG" # build or empty or build-version or -version
  - IMAGE_TAG=${IMAGE_TAG#-} && echo "IMAGE_TAG=$IMAGE_TAG" # build or empty or build-version or version
  - IMAGE_TAG=${IMAGE_TAG:+:$IMAGE_TAG} && echo "IMAGE_TAG=$IMAGE_TAG" # add leading : if not empty
  - IMAGE="$REPO/${RUNTIME}${IMAGE_TAG}" && echo "IMAGE=$IMAGE"
  - cd ${RUNTIME}${VARIANT:+/$VARIANT}

script:
  - docker build -t "$IMAGE" .
  - docker login -u $DOCKER_USER -p $DOCKER_PASS && docker push $IMAGE