sudo: required

language: bash
services: docker

env:
  - RUNTIME=python2.7 VARIANT=build
  # - RUNTIME=python3.6 VARIANT=build
  # - RUNTIME=nodejs4.4 VARIANT=build
  # - RUNTIME=nodejs6.10.3 VARIANT=build
  # - RUNTIME=nodejs8 VARIANT=build
  # - RUNTIME=java8 VARIANT=build

install:
  - 

before_script:
  - env | sort
  - cd "${RUNTIME}${VARIANT:+/$VARIANT}"
  - image="aliyunfc/${RUNTIME}${VARIANT:+:$VARIANT}"

script:
  - docker build -t "$image"