sudo: required

language: bash
services: docker

env:
  - RUNTIME=python2.7 VARIANT=build
  - RUNTIME=python2.7 VARIANT=run

  # - RUNTIME=python3.6 VARIANT=build
  # - RUNTIME=nodejs4.4 VARIANT=build
  # - RUNTIME=nodejs6.10.3 VARIANT=build
  # - RUNTIME=nodejs8 VARIANT=build
  # - RUNTIME=java8 VARIANT=build

# install:
#   - 

before_script:
  - env | sort
  - if [ "run" != "$VARIANT" ]; then IMAGE_TAG="$VARIANT" && echo "$IMAGE_TAG"; fi # build or empty
  # - if [ -n "$TRAVIS_TAG" ]; then WITH_VERSION="$IMAGE_TAG-$TRAVIS_TAG" && echo "WITH_VERSION=$WITH_VERSION"; fi 
  - WITH_VERSION=${TRAVIS_TAG:+$IMAGE_TAG-$TRAVIS_TAG} && echo "WITH_VERSION=$WITH_VERSION" # # build or empty or build-version or -version
  - IMAGE_TAG=${WITH_VERSION:-$IMAGE_TAG} && echo "IMAGE_TAG=$IMAGE_TAG" # build or empty or build-version or -version
  - IMAGE_TAG=${IMAGE_TAG#-} && echo "IMAGE_TAG=$IMAGE_TAG" # build or empty or build-version or version
  - IMAGE_TAG=${IMAGE_TAG:+:$IMAGE_TAG} && echo "IMAGE_TAG=$IMAGE_TAG" # add leading : if not empty
  - IMAGE="aliyunfc/${RUNTIME}${IMAGE_TAG}" && echo "IMAGE=$IMAGE"
  - cd ${RUNTIME}${VARIANT:+/$VARIANT}

script:
  - docker build -t "$IMAGE" .